/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author 84335
 */
public class BanHang_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form BanHang_JPanel
     */
    public BanHang_JPanel() {
        initComponents();
         setBounds(0, 0, 1020, 720);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_BH = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_BH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_BH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_BH.setText("Bán Hàng");
        add(lbl_BH, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 30, 229, 36));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_BH;
    // End of variables declaration//GEN-END:variables
}
