package gui;

import java.awt.Image;
import javax.swing.ImageIcon;

public class QuanLyDoiTra_JPanel extends javax.swing.JPanel {

    public QuanLyDoiTra_JPanel() {
        initComponents();
        setBounds(0, 0, 1020, 700);
        
        ImageIcon img_btnTimKiem = new ImageIcon("src//pic//buttonTimKiem.png");
        Image scaled_btnTimKiem = img_btnTimKiem.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnTimKiem = new ImageIcon(scaled_btnTimKiem);
        btn_TimKiem.setIcon(img_btnTimKiem);
        
        ImageIcon img_btnXemChiTiet = new ImageIcon("src//pic//buttonXemChiTiet.png");
        Image scaled_btnXemChiTiet = img_btnXemChiTiet.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnXemChiTiet = new ImageIcon(scaled_btnXemChiTiet);
        btn_XemChiTiet.setIcon(img_btnXemChiTiet);
        
        ImageIcon img_btnXoa = new ImageIcon("src//pic//buttonXoa.png");
        Image scaled_btnXoa = img_btnXoa.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnXoa = new ImageIcon(scaled_btnXoa);
        btn_Xoa.setIcon(img_btnXoa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel_TieuDeHoaDon = new javax.swing.JPanel();
        lbl_TieuDeHoaDon = new javax.swing.JLabel();
        Jpanel_ThaoTac = new javax.swing.JPanel();
        lbl_MaHoaDon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_MaDonDoiTra = new javax.swing.JTextField();
        jdc_NgaySinh = new com.toedter.calendar.JDateChooser();
        btn_TimKiem = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_XemChiTiet = new javax.swing.JButton();
        Jpanel_Table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_DanhSachDoiTra = new javax.swing.JTable();

        setBackground(new java.awt.Color(187, 205, 197));
        setMinimumSize(new java.awt.Dimension(1020, 700));
        setPreferredSize(new java.awt.Dimension(1000, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jpanel_TieuDeHoaDon.setBackground(new java.awt.Color(187, 205, 197));

        lbl_TieuDeHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_TieuDeHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDeHoaDon.setText("QUẢN LÝ ĐƠN ĐỔI TRẢ");
        Jpanel_TieuDeHoaDon.add(lbl_TieuDeHoaDon);

        add(Jpanel_TieuDeHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        Jpanel_ThaoTac.setBackground(new java.awt.Color(187, 205, 197));
        Jpanel_ThaoTac.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Các thao tác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        Jpanel_ThaoTac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MaHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbl_MaHoaDon.setText("Mã đơn đổi trả");
        Jpanel_ThaoTac.add(lbl_MaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 20, 120, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Ngày Lập");
        Jpanel_ThaoTac.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 60, 150, 20));

        txt_MaDonDoiTra.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_MaDonDoiTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaDonDoiTraActionPerformed(evt);
            }
        });
        Jpanel_ThaoTac.add(txt_MaDonDoiTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 200, 30));
        Jpanel_ThaoTac.add(jdc_NgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, 30));

        btn_TimKiem.setBackground(new java.awt.Color(0, 51, 51));
        btn_TimKiem.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_TimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });
        Jpanel_ThaoTac.add(btn_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 120, 30));

        btn_Xoa.setBackground(new java.awt.Color(204, 0, 0));
        btn_Xoa.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        Jpanel_ThaoTac.add(btn_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 120, 30));

        btn_XemChiTiet.setBackground(new java.awt.Color(0, 51, 51));
        btn_XemChiTiet.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_XemChiTiet.setForeground(java.awt.Color.white);
        btn_XemChiTiet.setText("Xem chi tiết");
        btn_XemChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_XemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XemChiTietActionPerformed(evt);
            }
        });
        Jpanel_ThaoTac.add(btn_XemChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 140, 30));

        add(Jpanel_ThaoTac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1000, 100));

        Jpanel_Table.setBackground(new java.awt.Color(187, 205, 197));
        Jpanel_Table.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Danh sách đơn đổi trả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        Jpanel_Table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Jpanel_Table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_DanhSachDoiTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đơn đổi trả", "Mã nhân viên", "Mã chi tiết hoá đơn", "Hình thức đổi trả", "Ngày lập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_DanhSachDoiTra);

        Jpanel_Table.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 980, 470));

        add(Jpanel_Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1000, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MaDonDoiTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaDonDoiTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaDonDoiTraActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_XemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XemChiTietActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_XemChiTietActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_Table;
    private javax.swing.JPanel Jpanel_ThaoTac;
    private javax.swing.JPanel Jpanel_TieuDeHoaDon;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_XemChiTiet;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdc_NgaySinh;
    private javax.swing.JLabel lbl_MaHoaDon;
    private javax.swing.JLabel lbl_TieuDeHoaDon;
    private javax.swing.JTable table_DanhSachDoiTra;
    private javax.swing.JTextField txt_MaDonDoiTra;
    // End of variables declaration//GEN-END:variables
}
