/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import bus.DanhMucSanPham_bus;
import entity.SanPhamEntity;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import bus.SanPham_bus;
import entity.ChatLieuEntity;
import entity.DanhMucSanPhamEntity;
import entity.KichThuocEnum;
import entity.MauSacEnum;
import entity.ThuongHieuEntity;
import entity.TinhTrangSPEnum;
import java.awt.Component;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import util.GenerateID;

/**
 *
 * @author 84335
 */
public class SanPham_JPanel extends javax.swing.JPanel {

//    private String fileName = null;
//    private byte[] imageSP = null;
    private String duongDanAnh = "D:\\HK1-NAM3\\PTUD\\AppDev_Project\\QuanLyCuaHangThoiTrang\\src\\pic\\labelAnh.png";
    private SanPham_bus sp_bus;
    private DanhMucSanPham_bus dmsp_bus;

    /**
     * Creates new form SanPham_JPanel
     */
    public SanPham_JPanel() {
        initComponents();
        //----------
        sp_bus = new SanPham_bus();
        dmsp_bus = new DanhMucSanPham_bus();
        //----------
        setBounds(0, 0, 1020, 720);
        ImageIcon img_btnTimKiem = new ImageIcon("src//pic//buttonTimKiem.png");
        Image scaled_btnTimKiem = img_btnTimKiem.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnTimKiem = new ImageIcon(scaled_btnTimKiem);
        btn_TimKiem.setIcon(img_btnTimKiem);
        ImageIcon img_btnLamMoi = new ImageIcon("src//pic//buttonLamMoi.png");
        Image scaled_btnLamMoi = img_btnLamMoi.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnLamMoi = new ImageIcon(scaled_btnLamMoi);
        btn_LamMoi.setIcon(img_btnLamMoi);
        ImageIcon img_btnThem = new ImageIcon("src//pic//buttonThem.png");
        Image scaled_btnThem = img_btnThem.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnThem = new ImageIcon(scaled_btnThem);
        btn_Them.setIcon(img_btnThem);
        ImageIcon img_btnCapNhat = new ImageIcon("src//pic//buttonCapNhat.png");
        Image scaled_btnCapNhat = img_btnCapNhat.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnCapNhat = new ImageIcon(scaled_btnCapNhat);
        btn_CapNhat.setIcon(img_btnCapNhat);
        ImageIcon img_btnKiemTraTonKho = new ImageIcon("src//pic//buttonKiemTraTonKho.png");
        Image scaled_btnKiemTraTonKho = img_btnKiemTraTonKho.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnKiemTraTonKho = new ImageIcon(scaled_btnKiemTraTonKho);
        btn_KiemTraTonKho.setIcon(img_btnKiemTraTonKho);
        ImageIcon img_btnChonAnh = new ImageIcon("src//pic//buttonChonAnh.png");
        Image scaled_btnChonAnh = img_btnChonAnh.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnChonAnh = new ImageIcon(scaled_btnChonAnh);
        btn_ChonAnh.setIcon(img_btnChonAnh);
        ImageIcon img_lblAnh = new ImageIcon("src//pic//labelAnh.png");
        Image scaled_lblAnh = img_lblAnh.getImage().getScaledInstance(150, 140, Image.SCALE_SMOOTH);
        img_lblAnh = new ImageIcon(scaled_lblAnh);
        lbl_AnhSanPham.setIcon(img_lblAnh);
        loadDuLieuTuDataLenTable();
        duaDuLieuVaComboboxoDanhMuc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_ThongTin = new javax.swing.JPanel();
        lbl_MaSanPham = new javax.swing.JLabel();
        lbl_TenSanPham = new javax.swing.JLabel();
        txt_MaSanPham = new javax.swing.JTextField();
        txt_TenSanPham = new javax.swing.JTextField();
        lbl_ThuongHieu = new javax.swing.JLabel();
        lbl_SoLuongTonKho = new javax.swing.JLabel();
        txt_ThuongHieu = new javax.swing.JTextField();
        txt_SoLuongTonKho = new javax.swing.JTextField();
        lbl_DanhMuc = new javax.swing.JLabel();
        cbo_DanhMuc = new javax.swing.JComboBox<>();
        lbl_KichThuoc = new javax.swing.JLabel();
        cbo_KichThuoc = new javax.swing.JComboBox<>();
        lbl_ChatLieu = new javax.swing.JLabel();
        txt_ChatLieu = new javax.swing.JTextField();
        lbl_MauSac = new javax.swing.JLabel();
        cbo_MauSac = new javax.swing.JComboBox<>();
        lbl_TinhTrang = new javax.swing.JLabel();
        cbo_TinhTrang = new javax.swing.JComboBox<>();
        lbl_DonGia = new javax.swing.JLabel();
        txt_DonGia = new javax.swing.JTextField();
        lbl_AnhSanPham = new javax.swing.JLabel();
        btn_ChonAnh = new javax.swing.JButton();
        panel_ThaoTac = new javax.swing.JPanel();
        lbl_MaSanPham_Search = new javax.swing.JLabel();
        btn_TimKiem = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        btn_CapNhat = new javax.swing.JButton();
        txt_MaSanPham_Search = new javax.swing.JTextField();
        btn_KiemTraTonKho = new javax.swing.JButton();
        panel_DanhSachSanPham = new javax.swing.JPanel();
        scroll_TableSanPham = new javax.swing.JScrollPane();
        Object[][] data={};
        String[] columnNames={"Mã","Tên sản phẩm", "Kích thước", "Màu sắc", "Đơn giá", "Tình trạng", "Số lượng", "Chất liệu", "Thương hiệu", "Danh mục"};
        model=new DefaultTableModel(data, columnNames){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        table_DanhSachSanPham = new javax.swing.JTable();
        lbl_TieuDe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(187, 205, 197));
        setPreferredSize(new java.awt.Dimension(1020, 700));

        panel_ThongTin.setBackground(new java.awt.Color(187, 205, 197));
        panel_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin nhà cung cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        lbl_MaSanPham.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_MaSanPham.setText("Mã sản phẩm");
        lbl_MaSanPham.setPreferredSize(new java.awt.Dimension(85, 15));

        lbl_TenSanPham.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_TenSanPham.setText("Tên sản phẩm");
        lbl_TenSanPham.setPreferredSize(new java.awt.Dimension(85, 15));

        txt_MaSanPham.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_MaSanPham.setEnabled(false);

        txt_TenSanPham.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbl_ThuongHieu.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_ThuongHieu.setText("Thương hiệu");
        lbl_ThuongHieu.setPreferredSize(new java.awt.Dimension(85, 15));

        lbl_SoLuongTonKho.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_SoLuongTonKho.setText("Số lượng tồn kho");
        lbl_SoLuongTonKho.setMaximumSize(new java.awt.Dimension(82, 15));
        lbl_SoLuongTonKho.setMinimumSize(new java.awt.Dimension(82, 15));
        lbl_SoLuongTonKho.setPreferredSize(new java.awt.Dimension(85, 15));

        txt_ThuongHieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_SoLuongTonKho.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbl_DanhMuc.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_DanhMuc.setText("Danh mục");
        lbl_DanhMuc.setPreferredSize(new java.awt.Dimension(85, 15));

        cbo_DanhMuc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbl_KichThuoc.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_KichThuoc.setText("Kích thước");
        lbl_KichThuoc.setPreferredSize(new java.awt.Dimension(85, 15));

        cbo_KichThuoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbo_KichThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL", "XXL" }));
        cbo_KichThuoc.setSelectedItem("S");

        lbl_ChatLieu.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_ChatLieu.setText("Chất liệu");
        lbl_ChatLieu.setPreferredSize(new java.awt.Dimension(85, 15));

        txt_ChatLieu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbl_MauSac.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_MauSac.setText("Màu sắc");
        lbl_MauSac.setPreferredSize(new java.awt.Dimension(85, 15));

        cbo_MauSac.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbo_MauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trắng", "Đen", "Xám" }));
        cbo_MauSac.setSelectedItem("Trắng");

        lbl_TinhTrang.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_TinhTrang.setText("Tình trạng");
        lbl_TinhTrang.setPreferredSize(new java.awt.Dimension(85, 15));

        cbo_TinhTrang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbo_TinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngừng bán", "Đang bán" }));
        cbo_TinhTrang.setSelectedItem("Đang bán");

        lbl_DonGia.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_DonGia.setText("Đơn giá");
        lbl_DonGia.setMaximumSize(new java.awt.Dimension(82, 15));
        lbl_DonGia.setMinimumSize(new java.awt.Dimension(82, 15));
        lbl_DonGia.setPreferredSize(new java.awt.Dimension(85, 15));

        txt_DonGia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lbl_AnhSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_ChonAnh.setBackground(new java.awt.Color(0, 51, 51));
        btn_ChonAnh.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_ChonAnh.setForeground(java.awt.Color.white);
        btn_ChonAnh.setText("Chọn ảnh");
        btn_ChonAnh.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_ChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ThongTinLayout = new javax.swing.GroupLayout(panel_ThongTin);
        panel_ThongTin.setLayout(panel_ThongTinLayout);
        panel_ThongTinLayout.setHorizontalGroup(
            panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ThongTinLayout.createSequentialGroup()
                        .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                                .addComponent(lbl_MaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_MaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                                .addComponent(lbl_TenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_TenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                                .addComponent(lbl_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                                .addComponent(lbl_ThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_ThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                                .addComponent(lbl_SoLuongTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_SoLuongTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                                .addComponent(lbl_DanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_ThongTinLayout.createSequentialGroup()
                        .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                                .addComponent(lbl_ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                                .addComponent(lbl_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                                .addComponent(lbl_TinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_TinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                                .addComponent(lbl_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_AnhSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        panel_ThongTinLayout.setVerticalGroup(
            panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                .addComponent(lbl_AnhSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(panel_ThongTinLayout.createSequentialGroup()
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MaSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ThuongHieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_ThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SoLuongTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SoLuongTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_TinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        panel_ThaoTac.setBackground(new java.awt.Color(187, 205, 197));
        panel_ThaoTac.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Các thao tác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        panel_ThaoTac.setPreferredSize(new java.awt.Dimension(932, 60));
        panel_ThaoTac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MaSanPham_Search.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_MaSanPham_Search.setText("Mã sản phẩm");
        panel_ThaoTac.add(lbl_MaSanPham_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, -1, -1));

        btn_TimKiem.setBackground(new java.awt.Color(0, 51, 51));
        btn_TimKiem.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_TimKiem.setForeground(java.awt.Color.white);
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_TimKiem.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });
        panel_ThaoTac.add(btn_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 19, 120, 30));

        btn_LamMoi.setBackground(new java.awt.Color(0, 51, 51));
        btn_LamMoi.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_LamMoi.setForeground(java.awt.Color.white);
        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_LamMoi.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_LamMoi.setPreferredSize(new java.awt.Dimension(90, 31));
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });
        panel_ThaoTac.add(btn_LamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 19, 120, 30));

        btn_Them.setBackground(new java.awt.Color(0, 51, 51));
        btn_Them.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_Them.setForeground(java.awt.Color.white);
        btn_Them.setText("Thêm");
        btn_Them.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Them.setPreferredSize(new java.awt.Dimension(90, 31));
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });
        panel_ThaoTac.add(btn_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 19, 120, 30));

        btn_CapNhat.setBackground(new java.awt.Color(0, 51, 51));
        btn_CapNhat.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_CapNhat.setForeground(java.awt.Color.white);
        btn_CapNhat.setText("Cập nhật");
        btn_CapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_CapNhat.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_CapNhat.setPreferredSize(new java.awt.Dimension(90, 31));
        panel_ThaoTac.add(btn_CapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 19, 120, 30));

        txt_MaSanPham_Search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panel_ThaoTac.add(txt_MaSanPham_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 21, 194, 25));

        btn_KiemTraTonKho.setBackground(new java.awt.Color(0, 51, 51));
        btn_KiemTraTonKho.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_KiemTraTonKho.setForeground(java.awt.Color.white);
        btn_KiemTraTonKho.setText("Kiểm tra kho hàng");
        btn_KiemTraTonKho.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        panel_ThaoTac.add(btn_KiemTraTonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 19, -1, 30));

        panel_DanhSachSanPham.setBackground(new java.awt.Color(187, 205, 197));
        panel_DanhSachSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bảng danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        panel_DanhSachSanPham.setPreferredSize(new java.awt.Dimension(1008, 317));

        table_DanhSachSanPham.setModel(model);
        table_DanhSachSanPham.getColumnModel().getColumn(0).setPreferredWidth(100);
        table_DanhSachSanPham.getColumnModel().getColumn(1).setPreferredWidth(200);
        table_DanhSachSanPham.getColumnModel().getColumn(2).setCellRenderer(new CenterRenderer());
        table_DanhSachSanPham.getColumnModel().getColumn(3).setCellRenderer(new CenterRenderer());
        table_DanhSachSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DanhSachSanPhamMouseClicked(evt);
            }
        });
        scroll_TableSanPham.setViewportView(table_DanhSachSanPham);

        javax.swing.GroupLayout panel_DanhSachSanPhamLayout = new javax.swing.GroupLayout(panel_DanhSachSanPham);
        panel_DanhSachSanPham.setLayout(panel_DanhSachSanPhamLayout);
        panel_DanhSachSanPhamLayout.setHorizontalGroup(
            panel_DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll_TableSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        panel_DanhSachSanPhamLayout.setVerticalGroup(
            panel_DanhSachSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll_TableSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        lbl_TieuDe.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_TieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDe.setText("QUẢN LÝ SẢN PHẨM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_ThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel_DanhSachSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_ThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(lbl_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_ThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_DanhSachSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void loadDuLieuTuDataLenTable() {
        ArrayList<SanPhamEntity> dsSanPham = sp_bus.getAllSanPham();
        for (SanPhamEntity sp : dsSanPham) {
            model.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getKichThuoc(),
                sp.getMauSac().toString(), sp.getDonGia(), sp.getTinhTrang().toString(),
                sp.getSoLuongTonKho(), sp.getChatLieu().getMaChatLieu(),
                sp.getThuongHieu().getMaThuongHieu(), sp.getDanhMucSanPham().getMaDanhMuc()});
        }
    }
    private void btn_ChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonAnhActionPerformed

        JFileChooser fileChooser = new JFileChooser("C:\\Users\\MY PC\\OneDrive\\Hình ảnh");
        fileChooser.setDialogTitle("Mở file");
        int kq = fileChooser.showOpenDialog(null);
        if (kq == JFileChooser.APPROVE_OPTION) {
            File tenAnh = fileChooser.getSelectedFile();
            duongDanAnh = tenAnh.getAbsolutePath();
            lbl_AnhSanPham.setIcon(ResizeImageIcon(String.valueOf(duongDanAnh)));
        } else if (kq == JFileChooser.CANCEL_OPTION) {

        } else {
            JOptionPane.showMessageDialog(null, "Lỗi chọn ảnh");
        }
    }//GEN-LAST:event_btn_ChonAnhActionPerformed
    private ImageIcon ResizeImageIcon(String ImagePath) {
        ImageIcon myIcon = new ImageIcon(ImagePath);
        Image img = myIcon.getImage().getScaledInstance(lbl_AnhSanPham.getWidth(), lbl_AnhSanPham.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img);
        return image;
    }
    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        themSanPham();
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void table_DanhSachSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DanhSachSanPhamMouseClicked
        // TODO add your handling code here:
        int row = table_DanhSachSanPham.getSelectedRow();
        txt_MaSanPham.setText(model.getValueAt(row, 0).toString());
        txt_TenSanPham.setText(model.getValueAt(row, 1).toString());
        cbo_KichThuoc.setSelectedItem(model.getValueAt(row, 2).toString());
        cbo_MauSac.setSelectedItem(model.getValueAt(row, 3).toString());
        txt_DonGia.setText(model.getValueAt(row, 4).toString());
        cbo_TinhTrang.setSelectedItem(model.getValueAt(row, 5).toString());
        txt_SoLuongTonKho.setText(model.getValueAt(row, 6).toString());
        txt_ChatLieu.setText(model.getValueAt(row, 7).toString());
        txt_ThuongHieu.setText(model.getValueAt(row, 8).toString());
        cbo_DanhMuc.setSelectedItem(model.getValueAt(row, 9).toString());
        kiemTraAnhNull(row);
//        lbl_AnhSanPham.setIcon(ResizeImageIcon(String.valueOf(sp_bus.getAllSanPham().get(row).getImgUrl())));
    }//GEN-LAST:event_table_DanhSachSanPhamMouseClicked

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        String ma = txt_MaSanPham_Search.getText().trim();
        timKiemSanPham(ma);

    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        lamMoi();
    }//GEN-LAST:event_btn_LamMoiActionPerformed
    private void kiemTraAnhNull(int row) {
        String img = sp_bus.getAllSanPham().get(row).getImgUrl();
        ImageIcon imageIcon;
        if (img != null) {
            imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_AnhSanPham.getWidth(), lbl_AnhSanPham.getHeight(), Image.SCALE_SMOOTH));
        } else {
            ImageIcon anhMacDinh = new ImageIcon("src//pic//labelAnh.png");
            imageIcon = new ImageIcon(anhMacDinh.getImage().getScaledInstance(lbl_AnhSanPham.getWidth(), lbl_AnhSanPham.getHeight(), Image.SCALE_SMOOTH));
        }
        lbl_AnhSanPham.setIcon(imageIcon);
    }

    private void themSanPham() {
        String maSP = GenerateID.sinhMa("SP");
        String tenSanPham = txt_TenSanPham.getText();
        KichThuocEnum kichThuoc = null;
        if (cbo_KichThuoc.getSelectedItem().equals("XS")) {
            kichThuoc = KichThuocEnum.XS;
        } else if (cbo_KichThuoc.getSelectedItem().equals("S")) {
            kichThuoc = KichThuocEnum.S;
        } else if (cbo_KichThuoc.getSelectedItem().equals("M")) {
            kichThuoc = KichThuocEnum.M;
        } else if (cbo_KichThuoc.getSelectedItem().equals("L")) {
            kichThuoc = KichThuocEnum.L;
        } else if (cbo_KichThuoc.getSelectedItem().equals("XL")) {
            kichThuoc = KichThuocEnum.XL;
        } else if (cbo_KichThuoc.getSelectedItem().equals("XXL")) {
            kichThuoc = KichThuocEnum.XXL;
        }
        MauSacEnum mauSac = null;
        if (cbo_MauSac.getSelectedItem().equals("Trắng")) {
            mauSac = MauSacEnum.TRANG;
        } else if (cbo_MauSac.getSelectedItem().equals("Đen")) {
            mauSac = MauSacEnum.DEN;
        } else if (cbo_MauSac.getSelectedItem().equals("Xám")) {
            mauSac = MauSacEnum.XAM;
        }
        double donGia = Double.parseDouble(txt_DonGia.getText().trim());
        TinhTrangSPEnum tinhTrang = null;
        if (cbo_TinhTrang.getSelectedItem().equals("Đang bán")) {
            tinhTrang = TinhTrangSPEnum.DANGBAN;
        } else if (cbo_TinhTrang.getSelectedItem().equals("Ngừng bán")) {
            tinhTrang = TinhTrangSPEnum.NGUNGBAN;
        }
        int soLuongTonKho = Integer.parseInt(txt_SoLuongTonKho.getText());
        String maChatLieu = txt_ChatLieu.getText();
        ChatLieuEntity chatLieu = new ChatLieuEntity(maChatLieu);
        String maThuongHieu = txt_ThuongHieu.getText();
        ThuongHieuEntity thuongHieu = new ThuongHieuEntity(maThuongHieu);
        String maDanhMuc = cbo_DanhMuc.getSelectedItem().toString();
        DanhMucSanPhamEntity danhMuc = new DanhMucSanPhamEntity(maDanhMuc);
        String anh = duongDanAnh;
        SanPhamEntity sp = new SanPhamEntity(maSP, tenSanPham, kichThuoc, mauSac, donGia, soLuongTonKho, tinhTrang, chatLieu, thuongHieu, danhMuc, anh);
        boolean kiemTra = sp_bus.themSP(sp);
        if (kiemTra) {
            model.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getKichThuoc(),
                sp.getMauSac().toString(), sp.getDonGia(), sp.getTinhTrang().toString(),
                sp.getSoLuongTonKho(), sp.getChatLieu().getMaChatLieu(),
                sp.getThuongHieu().getMaThuongHieu(), sp.getDanhMucSanPham().getMaDanhMuc()});
            JOptionPane.showMessageDialog(null, "Thêm thành công");
        } else {
            JOptionPane.showMessageDialog(null, "Thêm không thành công");
        }
    }

    private void timKiemSanPham(String ma) {
        model.setRowCount(0); // Đặt số hàng của bảng về 0 để xóa kết quả trước
        ArrayList<SanPhamEntity> dsSP = sp_bus.timSanPham(ma);
        if(dsSP.isEmpty()){
            JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm.");
            loadDuLieuTuDataLenTable();
        }else{
            for (SanPhamEntity sp : dsSP) {
            model.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(), sp.getKichThuoc(),
                sp.getMauSac().toString(), sp.getDonGia(), sp.getTinhTrang().toString(),
                sp.getSoLuongTonKho(), sp.getChatLieu().getMaChatLieu(),
                sp.getThuongHieu().getMaThuongHieu(), sp.getDanhMucSanPham().getMaDanhMuc()});
        }
        }
        
    }

    private void lamMoi() {
        txt_MaSanPham.setText("");
        txt_TenSanPham.setText("");
        txt_ChatLieu.setText("");
        txt_DonGia.setText("");
        txt_SoLuongTonKho.setText("");
        txt_ThuongHieu.setText("");
        cbo_KichThuoc.setSelectedItem("XS");
        cbo_MauSac.setSelectedItem("Trắng");
        cbo_DanhMuc.setSelectedIndex(0);
        cbo_TinhTrang.setSelectedItem("Đang bán");
        txt_MaSanPham_Search.setText("");
        model.setRowCount(0);
        ImageIcon anhMacDinh = new ImageIcon("src//pic//labelAnh.png");
        ImageIcon imageIcon = new ImageIcon(anhMacDinh.getImage().getScaledInstance(lbl_AnhSanPham.getWidth(), lbl_AnhSanPham.getHeight(), Image.SCALE_SMOOTH));
        lbl_AnhSanPham.setIcon(imageIcon);
        loadDuLieuTuDataLenTable();
    }

    private void duaDuLieuVaComboboxoDanhMuc() {
        ArrayList<DanhMucSanPhamEntity> dsDMSP = dmsp_bus.getAllDMSP();
        for (DanhMucSanPhamEntity dmsp : dsDMSP) {
            cbo_DanhMuc.addItem(dmsp.getMaDanhMuc());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_ChonAnh;
    private javax.swing.JButton btn_KiemTraTonKho;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JComboBox<String> cbo_DanhMuc;
    private javax.swing.JComboBox<String> cbo_KichThuoc;
    private javax.swing.JComboBox<String> cbo_MauSac;
    private javax.swing.JComboBox<String> cbo_TinhTrang;
    private javax.swing.JLabel lbl_AnhSanPham;
    private javax.swing.JLabel lbl_ChatLieu;
    private javax.swing.JLabel lbl_DanhMuc;
    private javax.swing.JLabel lbl_DonGia;
    private javax.swing.JLabel lbl_KichThuoc;
    private javax.swing.JLabel lbl_MaSanPham;
    private javax.swing.JLabel lbl_MaSanPham_Search;
    private javax.swing.JLabel lbl_MauSac;
    private javax.swing.JLabel lbl_SoLuongTonKho;
    private javax.swing.JLabel lbl_TenSanPham;
    private javax.swing.JLabel lbl_ThuongHieu;
    private javax.swing.JLabel lbl_TieuDe;
    private javax.swing.JLabel lbl_TinhTrang;
    private javax.swing.JPanel panel_DanhSachSanPham;
    private javax.swing.JPanel panel_ThaoTac;
    private javax.swing.JPanel panel_ThongTin;
    private javax.swing.JScrollPane scroll_TableSanPham;
    private javax.swing.JTable table_DanhSachSanPham;
    private DefaultTableModel model;
    private javax.swing.JTextField txt_ChatLieu;
    private javax.swing.JTextField txt_DonGia;
    private javax.swing.JTextField txt_MaSanPham;
    private javax.swing.JTextField txt_MaSanPham_Search;
    private javax.swing.JTextField txt_SoLuongTonKho;
    private javax.swing.JTextField txt_TenSanPham;
    private javax.swing.JTextField txt_ThuongHieu;
    // End of variables declaration//GEN-END:variables
}

class CenterRenderer extends DefaultTableCellRenderer {

    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        ((JLabel) c).setHorizontalAlignment(SwingConstants.CENTER); // Căn giữa nội dung của cột
        return c;
    }
}
