/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author 84335
 */
public class TaiKhoan_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaiKhoan_JPanel
     */
    public TaiKhoan_JPanel() {
        initComponents();
        setBounds(0, 0, 1020, 720);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_QuanLyTaiKhoan = new javax.swing.JPanel();
        lbl_QuanLyTaiKhoan = new javax.swing.JLabel();
        panel_ThaoTacTK = new javax.swing.JPanel();
        lbl_NhapTenTK = new javax.swing.JLabel();
        txt_NhapTenTK = new javax.swing.JTextField();
        btn_TimKiemTK = new javax.swing.JButton();
        btn_XoaTK = new javax.swing.JButton();
        panel_TableTaiKhoan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_DanhSachTK = new javax.swing.JTable();

        panel_QuanLyTaiKhoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl_QuanLyTaiKhoan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_QuanLyTaiKhoan.setText("Quản Lý Tài Khoản");

        javax.swing.GroupLayout panel_QuanLyTaiKhoanLayout = new javax.swing.GroupLayout(panel_QuanLyTaiKhoan);
        panel_QuanLyTaiKhoan.setLayout(panel_QuanLyTaiKhoanLayout);
        panel_QuanLyTaiKhoanLayout.setHorizontalGroup(
            panel_QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_QuanLyTaiKhoanLayout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(lbl_QuanLyTaiKhoan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_QuanLyTaiKhoanLayout.setVerticalGroup(
            panel_QuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_QuanLyTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_QuanLyTaiKhoan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_ThaoTacTK.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các thao tác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        lbl_NhapTenTK.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_NhapTenTK.setText("Nhập tên tài khoản");

        txt_NhapTenTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NhapTenTKActionPerformed(evt);
            }
        });

        btn_TimKiemTK.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_TimKiemTK.setText("Tìm kiếm");
        btn_TimKiemTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_XoaTK.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btn_XoaTK.setText("Xoá");
        btn_XoaTK.setToolTipText("");
        btn_XoaTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_XoaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ThaoTacTKLayout = new javax.swing.GroupLayout(panel_ThaoTacTK);
        panel_ThaoTacTK.setLayout(panel_ThaoTacTKLayout);
        panel_ThaoTacTKLayout.setHorizontalGroup(
            panel_ThaoTacTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThaoTacTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_NhapTenTK)
                .addGap(28, 28, 28)
                .addComponent(txt_NhapTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(btn_TimKiemTK)
                .addGap(18, 18, 18)
                .addComponent(btn_XoaTK)
                .addGap(150, 150, 150))
        );
        panel_ThaoTacTKLayout.setVerticalGroup(
            panel_ThaoTacTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThaoTacTKLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel_ThaoTacTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NhapTenTK)
                    .addComponent(txt_NhapTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiemTK)
                    .addComponent(btn_XoaTK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_TableTaiKhoan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng danh sách tài khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        table_DanhSachTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên tài khoản", "Thời gian đăng nhập gần nhất"
            }
        ));
        jScrollPane1.setViewportView(table_DanhSachTK);

        javax.swing.GroupLayout panel_TableTaiKhoanLayout = new javax.swing.GroupLayout(panel_TableTaiKhoan);
        panel_TableTaiKhoan.setLayout(panel_TableTaiKhoanLayout);
        panel_TableTaiKhoanLayout.setHorizontalGroup(
            panel_TableTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TableTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        panel_TableTaiKhoanLayout.setVerticalGroup(
            panel_TableTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TableTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_QuanLyTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_ThaoTacTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_TableTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_QuanLyTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_ThaoTacTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_TableTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NhapTenTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NhapTenTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NhapTenTKActionPerformed

    private void btn_XoaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XoaTKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TimKiemTK;
    private javax.swing.JButton btn_XoaTK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_NhapTenTK;
    private javax.swing.JLabel lbl_QuanLyTaiKhoan;
    private javax.swing.JPanel panel_QuanLyTaiKhoan;
    private javax.swing.JPanel panel_TableTaiKhoan;
    private javax.swing.JPanel panel_ThaoTacTK;
    private javax.swing.JTable table_DanhSachTK;
    private javax.swing.JTextField txt_NhapTenTK;
    // End of variables declaration//GEN-END:variables
}
