/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import bus.ChiTietHoaDon_bus;
import bus.DoiTra_bus;
import bus.HoaDon_bus;
import bus.SanPham_bus;
import entity.ChiTietHoaDonEntity;
import entity.DoiTraEntity;
import entity.HoaDonEntity;
import entity.NhanVienEntity;
import java.awt.Image;
import java.util.ArrayList;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.ConvertStringToEnum;
import util.GenerateID;
import util.ToanCuc;

/**
 *
 * @author 84335
 */
public class TaoDoiTra_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoiTra_JPanel
     */
    private HoaDon_bus hd_bus = new HoaDon_bus();
    private ChiTietHoaDon_bus cthd_bus = new ChiTietHoaDon_bus();
    private SanPham_bus sp_bus = new SanPham_bus();
    private DefaultTableModel tableModel;
    private GenerateID generateID = new GenerateID();
    private ToanCuc tc = new ToanCuc();
    private DoiTra_bus dt_bus = new DoiTra_bus();
    
    public TaoDoiTra_JPanel() {
        initComponents();
        setBounds(0, 0, 1020, 720);
         
        ImageIcon img_btnTimKiemHoaDon = new ImageIcon("src//pic//icon//buttonTimKiem.png");
        Image scaled_btnTimKiemHoaDon = img_btnTimKiemHoaDon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnTimKiemHoaDon = new ImageIcon(scaled_btnTimKiemHoaDon);
        btn_TimKiemHoaDon.setIcon(img_btnTimKiemHoaDon);
        
        ImageIcon img_btnTimKiemSanPham = new ImageIcon("src//pic//icon//buttonTimKiem.png");
        Image scaled_btnTimKiemSanPham = img_btnTimKiemSanPham.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnTimKiemSanPham = new ImageIcon(scaled_btnTimKiemSanPham);
        btn_TimKiemSanPham.setIcon(img_btnTimKiemSanPham);
        
        ImageIcon img_btnTaoDoiTra = new ImageIcon("src//pic//icon//buttonThem.png");
        Image scaled_btnTaoDoiTra = img_btnTaoDoiTra.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnTaoDoiTra = new ImageIcon(scaled_btnTaoDoiTra);
        btn_TaoDoiTra.setIcon(img_btnTaoDoiTra);
        
        ImageIcon img_btnLamMoi = new ImageIcon("src//pic//icon//buttonLamMoi.png");
        Image scaled_btnLamMoi = img_btnLamMoi.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        img_btnLamMoi = new ImageIcon(scaled_btnLamMoi);
        btn_LamMoi.setIcon(img_btnLamMoi); 
        
        // Table
        String[] cols = {"Mã", "Tên sản phẩm", "Kích thước", "Màu sắc", "Số lượng", "Giá bán", "Thành tiền"};
        tableModel = new DefaultTableModel(cols, 0);
        table_DanhSachHoaDon.setModel(tableModel);
        
        // Doi san pham khac
        txt_MaSanPhamKhac.setEditable(false);
        btn_TimKiemSanPham.setEnabled(false);
        spinner_SoLuongKhac.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_TaoDoiTra = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaHoaDon = new javax.swing.JTextField();
        btn_TimKiemHoaDon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_MaHoaDon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_TenKhachHang = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_NgayLap = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_SoDienThoai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_DanhSachHoaDon = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        lbl_TongTien = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_TienKhuyenMai = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_TienThanhToan = new javax.swing.JLabel();
        btn_LamMoi = new javax.swing.JButton();
        lbl_tongTien1 = new javax.swing.JLabel();
        lbl_KhuyenMai2 = new javax.swing.JLabel();
        lbl_thanhToan1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        spinner_SoLuong = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        radiobtn_HoanTra = new javax.swing.JRadioButton();
        radiobtn_DoiSanPham = new javax.swing.JRadioButton();
        txt_MaSanPham = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        lbl_TienHoanTra = new javax.swing.JLabel();
        btn_TaoDoiTra = new javax.swing.JButton();
        lbl_TienHoanTra1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        txt_MaSanPhamKhac = new javax.swing.JTextField();
        btn_TimKiemSanPham = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        lbl_TenSanPham = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbl_KichThuoc = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lbl_MauSac = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        spinner_SoLuongKhac = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        lbl_TienDu = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lbl_TienThem = new javax.swing.JLabel();
        lbl_TienHoanTra2 = new javax.swing.JLabel();
        lbl_TienHoanTra3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(187, 205, 197));
        setPreferredSize(new java.awt.Dimension(1000, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(187, 205, 197));

        lbl_TaoDoiTra.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_TaoDoiTra.setText("TẠO ĐƠN ĐỔI TRẢ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(lbl_TaoDoiTra)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_TaoDoiTra)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        jPanel2.setBackground(new java.awt.Color(187, 205, 197));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin hoá đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Mã hoá đơn");

        txt_MaHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        btn_TimKiemHoaDon.setBackground(new java.awt.Color(0, 51, 51));
        btn_TimKiemHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_TimKiemHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btn_TimKiemHoaDon.setText("Tìm kiếm");
        btn_TimKiemHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_TimKiemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemHoaDonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Mã hoá đơn");

        lbl_MaHoaDon.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_MaHoaDon.setText(" ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Tên khách hàng");

        lbl_TenKhachHang.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_TenKhachHang.setText(" ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Ngày lập");

        lbl_NgayLap.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_NgayLap.setText(" ");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Số điện thoại");

        lbl_SoDienThoai.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_SoDienThoai.setText(" ");

        table_DanhSachHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_DanhSachHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DanhSachHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_DanhSachHoaDon);
        if (table_DanhSachHoaDon.getColumnModel().getColumnCount() > 0) {
            table_DanhSachHoaDon.getColumnModel().getColumn(1).setPreferredWidth(200);
            table_DanhSachHoaDon.getColumnModel().getColumn(2).setPreferredWidth(20);
            table_DanhSachHoaDon.getColumnModel().getColumn(3).setPreferredWidth(50);
            table_DanhSachHoaDon.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("Tổng tiền");

        lbl_TongTien.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_TongTien.setText(" ");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setText("Tiền khuyến mãi");

        lbl_TienKhuyenMai.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_TienKhuyenMai.setText(" ");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel17.setText("Tiền phải thanh toán");

        lbl_TienThanhToan.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_TienThanhToan.setText(" ");

        btn_LamMoi.setBackground(new java.awt.Color(0, 51, 51));
        btn_LamMoi.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_LamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lbl_tongTien1.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_tongTien1.setText("VND");

        lbl_KhuyenMai2.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_KhuyenMai2.setText("VND");

        lbl_thanhToan1.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_thanhToan1.setText("VND");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_MaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_TimKiemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_MaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_tongTien1)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel13)
                                .addGap(30, 30, 30)
                                .addComponent(lbl_TienKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_KhuyenMai2)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel17)
                                .addGap(26, 26, 26)
                                .addComponent(lbl_TienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_thanhToan1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_MaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_MaHoaDon)
                    .addComponent(jLabel7)
                    .addComponent(lbl_NgayLap)
                    .addComponent(jLabel5)
                    .addComponent(lbl_TenKhachHang)
                    .addComponent(jLabel9)
                    .addComponent(lbl_SoDienThoai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbl_TongTien)
                    .addComponent(jLabel13)
                    .addComponent(lbl_TienKhuyenMai)
                    .addComponent(lbl_tongTien1)
                    .addComponent(lbl_KhuyenMai2)
                    .addComponent(jLabel17)
                    .addComponent(lbl_TienThanhToan)
                    .addComponent(lbl_thanhToan1))
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1000, 400));

        jPanel3.setBackground(new java.awt.Color(187, 205, 197));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin đơn đổi trả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel23.setText("Mã sản phẩm");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel25.setText("Số lượng");

        spinner_SoLuong.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        spinner_SoLuong.setEnabled(false);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel26.setText("Hình thức đổi trả");

        radiobtn_HoanTra.setBackground(new java.awt.Color(187, 205, 197));
        buttonGroup.add(radiobtn_HoanTra);
        radiobtn_HoanTra.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        radiobtn_HoanTra.setText("Hoàn trả");
        radiobtn_HoanTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_HoanTraActionPerformed(evt);
            }
        });

        radiobtn_DoiSanPham.setBackground(new java.awt.Color(187, 205, 197));
        buttonGroup.add(radiobtn_DoiSanPham);
        radiobtn_DoiSanPham.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        radiobtn_DoiSanPham.setText("Đổi sản phẩm khác");
        radiobtn_DoiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_DoiSanPhamActionPerformed(evt);
            }
        });

        txt_MaSanPham.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel24.setText("Tiền hoàn trả");

        lbl_TienHoanTra.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_TienHoanTra.setText(" ");

        btn_TaoDoiTra.setBackground(new java.awt.Color(0, 51, 51));
        btn_TaoDoiTra.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_TaoDoiTra.setForeground(new java.awt.Color(255, 255, 255));
        btn_TaoDoiTra.setText("Tạo đơn đổi trả");
        btn_TaoDoiTra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_TaoDoiTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoDoiTraActionPerformed(evt);
            }
        });

        lbl_TienHoanTra1.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_TienHoanTra1.setText("VND");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_MaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(spinner_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(radiobtn_HoanTra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radiobtn_DoiSanPham))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btn_TaoDoiTra, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(84, 84, 84))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_TienHoanTra, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_TienHoanTra1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(spinner_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(radiobtn_HoanTra)
                    .addComponent(radiobtn_DoiSanPham))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lbl_TienHoanTra)
                    .addComponent(lbl_TienHoanTra1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btn_TaoDoiTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 510, 200));

        jPanel4.setBackground(new java.awt.Color(187, 205, 197));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin sản phẩm khác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel28.setText("Mã sản phẩm");

        txt_MaSanPhamKhac.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        btn_TimKiemSanPham.setBackground(new java.awt.Color(0, 51, 51));
        btn_TimKiemSanPham.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_TimKiemSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btn_TimKiemSanPham.setText("Tìm kiếm");
        btn_TimKiemSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel29.setText("Tên sản phẩm");

        lbl_TenSanPham.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_TenSanPham.setText(" ");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel31.setText("Kích thước");

        lbl_KichThuoc.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_KichThuoc.setText(" ");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel33.setText("Màu sắc");

        lbl_MauSac.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_MauSac.setText(" ");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel35.setText("Số lượng");

        spinner_SoLuongKhac.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel36.setText("Tiền dư trả lại");

        lbl_TienDu.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_TienDu.setText(" ");

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel38.setText("Tiền phải trả thêm");

        lbl_TienThem.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_TienThem.setText(" ");

        lbl_TienHoanTra2.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_TienHoanTra2.setText("VND");

        lbl_TienHoanTra3.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lbl_TienHoanTra3.setText("VND");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txt_MaSanPhamKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_TimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_TenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(lbl_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(lbl_TienDu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_TienHoanTra2)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel35)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(spinner_SoLuongKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel31)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lbl_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lbl_TienHoanTra3)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_TienThem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_MaSanPhamKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TenSanPham)
                            .addComponent(jLabel31)
                            .addComponent(lbl_KichThuoc))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_MauSac)
                                .addComponent(jLabel35)
                                .addComponent(spinner_SoLuongKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(lbl_TienDu)
                    .addComponent(lbl_TienHoanTra2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(lbl_TienThem)
                    .addComponent(lbl_TienHoanTra3))
                .addGap(20, 20, 20))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 480, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void radiobtn_HoanTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_HoanTraActionPerformed
        int row = table_DanhSachHoaDon.getSelectedRow();
        if(row < 0) {
            JOptionPane.showMessageDialog(this, "Sản phẩm chưa được chọn!");
            return;
        }
        double thanhTien = Double.parseDouble(table_DanhSachHoaDon.getValueAt(row, 6).toString());
        lbl_TienHoanTra.setText(thanhTien+"");
        
        txt_MaSanPhamKhac.setText("");
        txt_MaSanPhamKhac.setEditable(false);
        btn_TimKiemSanPham.setEnabled(false);
        spinner_SoLuongKhac.setEnabled(false);
        lbl_TenSanPham.setText("");
        lbl_KichThuoc.setText("");
        lbl_MauSac.setText("");
        spinner_SoLuongKhac.setValue(0);
        lbl_TienDu.setText("");
        lbl_TienThem.setText("");
    }//GEN-LAST:event_radiobtn_HoanTraActionPerformed

    private void btn_TaoDoiTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoDoiTraActionPerformed
        taoDonDoiTra();
    }//GEN-LAST:event_btn_TaoDoiTraActionPerformed

    private void table_DanhSachHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DanhSachHoaDonMouseClicked
        int row = table_DanhSachHoaDon.getSelectedRow();
        if(row < 0) {
            JOptionPane.showMessageDialog(this, "Sản phẩm chưa được chọn!");
            return;
        }
        String maSP = table_DanhSachHoaDon.getValueAt(row, 0).toString();
        txt_MaSanPham.setText(maSP);
        int soLuong = Integer.parseInt(table_DanhSachHoaDon.getValueAt(row, 4).toString());
        spinner_SoLuong.setValue(soLuong);
        radiobtn_HoanTra.setSelected(true);
        double thanhTien = Double.parseDouble(table_DanhSachHoaDon.getValueAt(row, 6).toString());
        lbl_TienHoanTra.setText(thanhTien+"");
    }//GEN-LAST:event_table_DanhSachHoaDonMouseClicked

    private void btn_TimKiemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemHoaDonActionPerformed
        timKiemHoaDon();
    }//GEN-LAST:event_btn_TimKiemHoaDonActionPerformed

    private void radiobtn_DoiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_DoiSanPhamActionPerformed
        txt_MaSanPhamKhac.setEditable(true);
        btn_TimKiemSanPham.setEnabled(true);
        spinner_SoLuongKhac.setEnabled(true);
        lbl_TienHoanTra.setText("0");
    }//GEN-LAST:event_radiobtn_DoiSanPhamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_TaoDoiTra;
    private javax.swing.JButton btn_TimKiemHoaDon;
    private javax.swing.JButton btn_TimKiemSanPham;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_KhuyenMai2;
    private javax.swing.JLabel lbl_KichThuoc;
    private javax.swing.JLabel lbl_MaHoaDon;
    private javax.swing.JLabel lbl_MauSac;
    private javax.swing.JLabel lbl_NgayLap;
    private javax.swing.JLabel lbl_SoDienThoai;
    private javax.swing.JLabel lbl_TaoDoiTra;
    private javax.swing.JLabel lbl_TenKhachHang;
    private javax.swing.JLabel lbl_TenSanPham;
    private javax.swing.JLabel lbl_TienDu;
    private javax.swing.JLabel lbl_TienHoanTra;
    private javax.swing.JLabel lbl_TienHoanTra1;
    private javax.swing.JLabel lbl_TienHoanTra2;
    private javax.swing.JLabel lbl_TienHoanTra3;
    private javax.swing.JLabel lbl_TienKhuyenMai;
    private javax.swing.JLabel lbl_TienThanhToan;
    private javax.swing.JLabel lbl_TienThem;
    private javax.swing.JLabel lbl_TongTien;
    private javax.swing.JLabel lbl_thanhToan1;
    private javax.swing.JLabel lbl_tongTien1;
    private javax.swing.JRadioButton radiobtn_DoiSanPham;
    private javax.swing.JRadioButton radiobtn_HoanTra;
    private javax.swing.JSpinner spinner_SoLuong;
    private javax.swing.JSpinner spinner_SoLuongKhac;
    private javax.swing.JTable table_DanhSachHoaDon;
    private javax.swing.JTextField txt_MaHoaDon;
    private javax.swing.JTextField txt_MaSanPham;
    private javax.swing.JTextField txt_MaSanPhamKhac;
    // End of variables declaration//GEN-END:variables
    
    public void timKiemHoaDon() {
        String maHD = txt_MaHoaDon.getText().trim();
        if(maHD.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã hoá đơn chưa được nhập!");
            return;
        }
        
        HoaDonEntity hoaDon = hd_bus.timKiemHoaDonTheoMa(maHD);
        if(hoaDon != null) {
            lbl_MaHoaDon.setText(hoaDon.getMaHD());
            lbl_TenKhachHang.setText(hoaDon.getKhachHang().getHoTen());
            lbl_SoDienThoai.setText(hoaDon.getKhachHang().getSoDienThoai());
            lbl_NgayLap.setText(hoaDon.getNgayLapHD().toString());
            lbl_TongTien.setText(hoaDon.getTongTien()+"");
            lbl_TienKhuyenMai.setText(hoaDon.getTienKhuyenMai()+"");
            lbl_TienThanhToan.setText(hoaDon.getTienThanhToan()+"");
            ArrayList<ChiTietHoaDonEntity> cthdList = cthd_bus.getAllCTHDTheoMaHD(maHD);
            if(cthdList != null) {
                tableModel.setRowCount(0);
                for (ChiTietHoaDonEntity cthd : cthdList) {
                    String[] data = {cthd.getSanPham().getMaSP(), cthd.getSanPham().getTenSP(), cthd.getSanPham().getKichThuoc().toString(), cthd.getSanPham().getMauSac().toString(), 
                    cthd.getSoLuong()+"", cthd.getGiaBan()+"", cthd.getThanhTien()+""};
                    tableModel.addRow(data);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hoá đơn không tồn tại!");
        }
    }
    
    public void taoDonDoiTra() {
        if(!radiobtn_HoanTra.isSelected() && !radiobtn_DoiSanPham.isSelected()) {
            JOptionPane.showMessageDialog(this, "Hình thức đổi trả chưa chọn!");
            return;
        }
        String maDYCDT = generateID.sinhMa("DT");
        String maHD = lbl_MaHoaDon.getText().trim();
        HoaDonEntity hd = new HoaDonEntity(maHD);
        String maNV = tc.getMa();
        NhanVienEntity nv = new NhanVienEntity(maNV);
        Date thoiGian = Date.valueOf(LocalDate.now());
        
        ConvertStringToEnum toEnum = new ConvertStringToEnum();
        String hinhThuc = "Hoàn trả";
        if(radiobtn_DoiSanPham.isSelected()) {
            hinhThuc = "Đổi sản phẩm khác";
        }
        
        DoiTraEntity dt = new DoiTraEntity(maDYCDT, hd, nv, toEnum.HinhThucDTToEnum(hinhThuc), thoiGian);
        
        boolean kq = dt_bus.taoDoiTra(dt);
        if(kq) {
            JOptionPane.showMessageDialog(this, "Tạo đơn đổi trả thàng công!");
            lamMoi();
        } else {
            JOptionPane.showMessageDialog(this, "Tạo đơn đổi trả thất bại!");
        }
    }
    
    public void lamMoi() {
        txt_MaHoaDon.setText("");
        lbl_MaHoaDon.setText("");
        lbl_TenKhachHang.setText("");
        lbl_SoDienThoai.setText("");
        lbl_NgayLap.setText("");
        lbl_TongTien.setText("");
        lbl_TienKhuyenMai.setText("");
        lbl_TienThanhToan.setText("");
        
        tableModel.setRowCount(0);
        table_DanhSachHoaDon.clearSelection();
        
        txt_MaSanPham.setText("");
        spinner_SoLuong.setValue(0);
        radiobtn_HoanTra.setSelected(false);
        radiobtn_DoiSanPham.setSelected(false);
        lbl_TienHoanTra.setText("");
        
        txt_MaSanPhamKhac.setText("");
        txt_MaSanPhamKhac.setEditable(false);
        btn_TimKiemSanPham.setEnabled(false);
        spinner_SoLuongKhac.setEnabled(false);
        lbl_TenSanPham.setText("");
        lbl_KichThuoc.setText("");
        lbl_MauSac.setText("");
        spinner_SoLuongKhac.setValue(0);
        lbl_TienDu.setText("");
        lbl_TienThem.setText("");
   }
}
