/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author 84335
 */
public class TrangChu_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrangChu_JPanel
     */
    public TrangChu_JPanel() {
        initComponents();
        setVisible(true);
        setBounds(0, 0, 1020, 720);
         ImageIcon img_TrangChu = new ImageIcon("src\\pic\\hinhnenTrangChu.png");
    Image scaled_TrangChu = img_TrangChu.getImage().getScaledInstance(1020, 720, Image.SCALE_SMOOTH);
    img_TrangChu = new ImageIcon(scaled_TrangChu);
    lbl_IConTrangChu.setIcon(img_TrangChu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_IConTrangChu = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(lbl_IConTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 720));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_IConTrangChu;
    // End of variables declaration//GEN-END:variables
}
